### ISSUE TITLE
Outdated launchdarkly-js-client-sdk package reference.

### ISSUE THREAD

**Issue by bradlis7** [launchdarkly/vue-client-sdk#13]
Currently you reference launchdarkly-js-client-sdk 2.24.2. But 3.1.2 is available. This causes npm to spit out this warning.

```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by yusinto** [comment]
Thank you for reporting this. The js sdk [v3 is a major update](https://github.com/launchdarkly/js-client-sdk/releases/tag/3.0.0) which includes breaking changes to support contexts instead of users. It's not a simple version bump on the vue sdk to support contexts but we are working on it. It looks like this is only a warning so it should be ok for now to ignore. Thank you for your patience.

**Comment by marcusball** [comment]
I don't know how you prefer to handle version changes, but I have a fork with the package updated with the newest SDK version. Would you accept that as a PR to help with updating it?
