### ISSUE TITLE
Need to refresh the page twice to see the new flag value after updating it

### ISSUE THREAD

**Issue by pandyarudra** [launchdarkly/vue-client-sdk#28]
I am using  "launchdarkly-vue-client-sdk": "^2.0.2", and I have setup the launch darkly plugin in the `VueApp.use(LDPlugin, { clientSideId: 'xyz' }); `. I have created a wrapper function to read the values from Launch Darkly, i.e. 

`const useFeatureFlag = (flagName: string) => {  return useLDFlag(flagName);  }`

and I'm using it like this: 
```

<template>
     <div v-if="testFlag"></div>
</template>
<script setup>
const testFlag = useFeatureFlag('TestFlag');
</script>
```

Now, whenever I change the value of the flag from false to true in the Portal, it doesn't pickup the true value and I need to refresh page twice to see the changes being reflected. I don't want the live-stream changes and have disabled the `streaming` option

No Logs 
SDK Version: 2.0.2

**Comment by yusinto** [comment]
@pandyarudra the way you invoke your `useFeatureFlag` function in `<script setup>` means `useFeatureFlag` is only run once on component creation. No updates will be made since you set streaming to false.

Please try calling `useFeatureFlag('TestFlag')` directly in your `<template>` code so your component will always render the latest flag values.

Please reach out to our support team if you need further help on this issue.

**Comment by pandyarudra** [comment]
Thanks for your reply, I'll give it a try. I was under the impression that it's reactive, so value would reflect in the template automatically on updates.

I'll let you know after trying.
